# /mnt/data/config.yaml
mqtt:
  broker: "localhost"     # or IP of your MQTT broker
  port: 1883
  keepalive: 60

sensors:
  kitchen:
    heater:
      temp: "kitchen/heater/temp"
      rh: "kitchen/heater/rh"
  kids:
    heater:
      temp: "kids/heater/temp"
      rh: "kids/heater/rh"
  bedroom:
    heater:
      temp: "bedroom/heater/temp"
      rh: "bedroom/heater/rh"
    ceiling:
      temp: "bedroom/ceiling/temp"
      rh: "bedroom/ceiling/rh"      
