#!/bin/sh /etc/rc.common

START=99
STOP=10

SERVICE_NAME="mqtt_logg_service"
SCRIPT="/mnt/data/log_mqtt.sh"

USE_PROCD=1

start_service() {
    mkdir -p /mnt/data/logs

    procd_open_instance

    procd_set_param command /bin/sh "$SCRIPT"

    # Restart if it crashes
    procd_set_param respawn 5 1 0

    # Optional: nice logging
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {
    # procd handles stopping automatically
    return 0
}
